# Generated by Django 3.2.5 on 2021-12-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=200, unique=True)),
                ('application_domain', models.CharField(max_length=500)),
                ('application_owner', models.CharField(max_length=100)),
                ('application_team_dl', models.CharField(max_length=500)),
                ('change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dbconnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=200, unique=True)),
                ('db_name', models.CharField(max_length=500)),
                ('db_user_name', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=500)),
                ('db_host_name', models.CharField(max_length=500)),
                ('db_type', models.CharField(max_length=200)),
                ('change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='testcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=100)),
                ('testcase_desc', models.CharField(max_length=500)),
                ('source_query', models.CharField(max_length=5000)),
                ('target_query', models.CharField(max_length=5000)),
                ('source_connection_name', models.CharField(max_length=500)),
                ('target_connection_name', models.CharField(max_length=500)),
                ('source_table_name', models.CharField(max_length=100)),
                ('target_table_name', models.CharField(max_length=100)),
                ('change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='testresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('testcases_id', models.IntegerField()),
                ('source_result', models.CharField(max_length=500)),
                ('target_result', models.CharField(max_length=500)),
                ('change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
