# Generated by Django 3.2.5 on 2021-12-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raindrop', '0002_auto_20211211_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='tcresultview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.IntegerField()),
                ('testcase_desc', models.CharField(max_length=100)),
                ('source_result', models.CharField(max_length=500)),
                ('target_result', models.CharField(max_length=500)),
                ('result_type', models.CharField(max_length=500)),
                ('change_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'raindrop_testresult_view',
                'managed': False,
            },
        ),
    ]
