# Generated by Django 3.2.5 on 2021-12-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raindrop', '0003_tcresultview'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=500)),
            ],
        ),
    ]
