# Generated by Django 3.2.5 on 2021-12-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raindrop', '0008_remove_testrescompare_pk_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrescompare',
            name='result_status',
        ),
        migrations.AddField(
            model_name='testcases',
            name='pk_column',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
