# Generated by Django 3.2.5 on 2021-12-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raindrop', '0009_auto_20211220_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrescompare',
            name='pk_column',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
