# Generated by Django 3.2.5 on 2021-12-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raindrop', '0011_testrescompare_result_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrescompare',
            name='source_result',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testrescompare',
            name='target_result',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
