# Generated by Django 3.2.5 on 2021-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raindrop', '0012_auto_20211223_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrescompare',
            name='pk_value',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
    ]
